Correct toolchain with alienv on Ubuntu and Debian
Supported Ubuntus: 14.04, 15.10
Supported Debians: 8

diff --git a/cvmfs/alienv b/cvmfs/alienv
--- a/cvmfs/alienv
+++ b/cvmfs/alienv
@@ -77,8 +77,12 @@ case $distro_name in
         uname_m=`uname -m`
         arch=${uname_m}-2.6-gnu-4.1.2
         case $distro_release in
-           6.*|7.*|8.*)
+           6.*|6|7.*|7)
               distro_xrelease=6.x
+              ;;
+           8.*|8)
+              distro_xrelease=6.x
+              platform=ubuntu1404
               ;;
         esac
         ;;
@@ -87,8 +91,12 @@ case $distro_name in
         uname_m=`uname -m`
         arch=${uname_m}-2.6-gnu-4.1.2
         case $distro_release in
-           13.*|14.*|15.*)
+           13.*)
               distro_xrelease=6.x
+              ;;
+           14.*|15.*)
+              distro_xrelease=6.x
+              platform=ubuntu1404
               ;;
         esac
         ;;
@@ -126,6 +134,29 @@ function modulepath {
     fi
   done
   printf "\n" 
+}
+
+function test_toolchain {
+  local TMPPREF=/tmp/alienv_helloworld
+  cat > $TMPPREF.cpp <<EOF
+#include <iostream>
+int main(int argn, char *argv) {
+  std::cout << "hello world" << std::endl;
+  return 0;
+}
+EOF
+  g++ -o $TMPPREF ${TMPPREF}.cpp > ${TMPPREF}.log 2>&1
+  if [[ `/tmp/alienv_helloworld 2> /dev/null` != "hello world" ]]; then
+    echo "WARNING: We are using GNU C++ compiler at $(which g++ 2> /dev/null)" >&2
+    echo "WARNING: This compiler is unable to produce valid executables on this platform!" >&2
+    echo "WARNING: Error from g++ follows:" >&2
+    while IFS= read LINE; do
+      echo "WARNING: $LINE" >&2
+    done < <(cat ${TMPPREF}.log)
+  else
+    echo "NOTICE: loaded compiler ($(which g++)) seems to produce valid executables" >&2
+  fi
+  rm -f ${TMPPREF}*
 }
 
 export MODULEPATH=$(modulepath modulefiles $moduledirs)
@@ -198,6 +229,7 @@ do
        else
           alienvrc=""
        fi
+       [ x$ALIENV_DEBUG == x1 ] && test_toolchain
        exec env PS1="[$args] \W > " bash --norc $alienvrc -i
        ;;
      setenv)
@@ -209,6 +241,7 @@ do
          $moduleenv $modulecmd bash list 2>&1 | grep -q AliEn-Runtime ) || \
          toload="$alien$alien_version $args"
        Eval $moduleenv $modulecmd bash load $toload || exit 1
+       [ x$ALIENV_DEBUG == x1 ] && test_toolchain
        shift 1
        ;;
      printenv)
@@ -224,6 +257,7 @@ do
          $moduleenv $modulecmd bash list 2>&1 | grep -q AliEn-Runtime ) || \
          toload="$alien$alien_version $args"
        $moduleenv $modulecmd bash load $toload || exit 1
+       [ x$ALIENV_DEBUG == x1 ] && test_toolchain
        exit
        ;;
      -print)
