Add platform priorities to alienv

diff --git a/cvmfs/alienv b/cvmfs/alienv
--- a/cvmfs/alienv
+++ b/cvmfs/alienv
@@ -2,10 +2,23 @@
 
 version=3.2.10
 cvmfsdir=/cvmfs/alice.cern.ch
-path=`dirname $0`
+
+prog=`readlink $0 2>/dev/null`
+[[ -z $prog ]] && prog=$0
+path=`dirname $prog`
 path=`cd "$path";pwd`
-[[ `basename "$path"` == bin ]] && cvmfsdir=`dirname "$path"`
+[ x$ALIENV_DEBUG == x1 ] && printf "path=$path\nprog=$prog\n" >&2
+
+if [[ `basename $prog` == alienv && `basename $path` == bin ]]; then
+  cvmfsdir=`dirname "$path"`
+else
+  [ x$ALIENV_DEBUG == x1 ] && printf "WARNING: cannot autodetect CVMFS path, falling back to $cvmfsdir\n" >&2
+fi
+
+path=$(cd $(dirname $0) && pwd) # appended to PATH later on
 printvar=""
+
+[ x$ALIENV_DEBUG == x1 ] && printf "cvmfsdir=$cvmfsdir\npath=$path\n" >&2
 
 Eval(){
    cmd=$*
@@ -132,9 +145,6 @@ fi
 
 unset MODULESHOME
 
-moduledirs="$modulepath $cvmfsdir/x86_64-2.6-gnu-4.1.2 $cvmfsdir/x86_64-2.6-gnu-4.7.2 $cvmfsdir/x86_64-2.6-gnu-4.8.3 $cvmfsdir/x86_64-2.6-gnu-4.8.4"
-[ x$platform != x ] && moduledirs="$moduledirs $cvmfsdir/${platform}-${uname_m}"
-
 function modulepath {
   local dir
   local colon
@@ -193,10 +203,6 @@ function load_alien_if_missing {
   return 0
 }
 
-export MODULEPATH=$(modulepath modulefiles $moduledirs)
-[ x$platform != x ] && MODULEPATH="$cvmfsdir/etc/toolchain/modulefiles/${platform}-${uname_m}:$MODULEPATH"
-[ x$ALIENV_DEBUG == x1 ] && printf "MODULEPATH=$MODULEPATH\n" >&2
-
 export PATH=$PATH:$path
 
 if [  -d $modules/$version/$distro_dir/$distro_release ]
@@ -233,6 +239,56 @@ fi
 alien="AliEn"
 
 export ALIEN_ORGANISATION=$(tr "[:lower:]" "[:upper:]" <<< "${ALIEN_ORGANISATION:=ALICE}")
+
+# We cannot cross-pick pacakages among different platforms but we have to
+# pick all packages consistently from a certain platform tree. When listing
+# packages we show them all, when we load a package e define a priority list and
+# we always have a fallback for backward compatibility.
+PLATFORM_PRIORITY="el6-x86_64 el5-x86_64"
+ARGS=("$@")
+PACKAGES=
+EXPECT_PACKAGES=
+for ARG in "$@"; do
+  if [[ $EXPECT_PACKAGES == 1 ]]; then
+    PACKAGES=`echo $ARG | sed -e "s%VO_$ALIEN_ORGANISATION@%%g" -e 's%::%/%g' -e 's%,% %g'`
+    break
+  elif [[ "$ARG" == enter || "$ARG" == printenv || "$ARG" == setenv ]]; then
+    EXPECT_PACKAGES=1
+  else
+    EXPECT_PACKAGES=
+  fi
+done
+if [[ x"$PACKAGES" != x ]]; then
+  for P in $PLATFORM_PRIORITY; do
+    [[ "${P:0:3}" == el5 ]] && P="$cvmfsdir/x86_64-2.6-gnu-4.1.2
+                                  $cvmfsdir/x86_64-2.6-gnu-4.7.2
+                                  $cvmfsdir/x86_64-2.6-gnu-4.8.3
+                                  $cvmfsdir/x86_64-2.6-gnu-4.8.4" \
+                            || P="$cvmfsdir/$P"
+    moduledirs="`echo $modulepath $P`"
+    export MODULEPATH=$(modulepath modulefiles $moduledirs)
+    [ x$platform != x ] && MODULEPATH="$cvmfsdir/etc/toolchain/modulefiles/${platform}-${uname_m}:$MODULEPATH"
+    LOADED="`Eval $moduleenv $modulecmd bash load $PACKAGES > /dev/null 2>&1 ; echo "$_LMFILES_"`"
+    OK=1
+    for X in $PACKAGES; do
+      # Policy: all specified packages must be found in current platform. If
+      # this is not the case then fallback on the next platform.
+      echo $LOADED | grep -q $X || { OK=0; break; }
+    done
+    [ x$OK == x1 ] && break || { [ x$ALIENV_DEBUG == x1 ] && printf "WARNING: cannot find packages with MODULEPATH set to $MODULEPATH\n"; }
+  done
+else
+  moduledirs="`echo "$modulepath
+                     $cvmfsdir/x86_64-2.6-gnu-4.1.2
+                     $cvmfsdir/x86_64-2.6-gnu-4.7.2
+                     $cvmfsdir/x86_64-2.6-gnu-4.8.3
+                     $cvmfsdir/x86_64-2.6-gnu-4.8.4
+                     $cvmfsdir/el6-x86_64"`"
+  export MODULEPATH=$(modulepath modulefiles $moduledirs)
+  [ x$platform != x ] && MODULEPATH="$cvmfsdir/etc/toolchain/modulefiles/${platform}-${uname_m}:$MODULEPATH"
+fi
+
+[ x$ALIENV_DEBUG == x1 ] && printf "MODULEPATH=$MODULEPATH\n" >&2
 
 while [ $# -gt 0 ]
 do
